services:
    mongodb:
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        image: mongo:latest
        container_name: mongo_bridge
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongodb:/data/db
            - ./data:/data/db
            - ./scripts:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_ROOT_USERNAME: m
            MONGO_INITDB_ROOT_PASSWORD: m
